import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Renders the application shell, the request's client IP address, and the route content.
 *
 * The first available forwarded, real, or remote address is logged and displayed before
 * `children`; an IPv6 loopback address is displayed as `127.0.0.1`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const ip =
    headersList.get('x-forwarded-for') ||
    headersList.get('x-real-ip') ||
    headersList.get('remote-addr');

  console.log(ip);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {ip === '::1' ? '127.0.0.1' : ip}
        {children}
      </body>
    </html>
  );
}
